"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import React,{useEffect,useMemo,useState} from "react";
import {createExpenseV2,createPurchaseV2,listProductsV2,recentExpensesV2,updateExpenseV2,upsertProductV2,voidExpenseV2} from "./data-api-v2";

const today=new Date().toISOString().slice(0,10);
const money=(n:number)=>`¥ ${Number(n||0).toLocaleString("zh-CN",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
type Line={productId:number|null;item:string;category:string;qty:number;unit:string;price:number};
type Product={id:number;name:string;category:string;brand:string;spec:string;unit:string;stocktake:boolean;reminder:boolean;active:boolean};
const blankLine=():Line=>({productId:null,item:"",category:"",qty:1,unit:"—",price:0});
const productCategories=["食材","调料","食用油","米面粮油","酒水","餐具类","日化类","纸品类","其他"];
const units=["kg","斤","箱","包","个","瓶","桶","袋","盒"];

export default function ExpensesV2({expenseCategories,toast,go}:{expenseCategories:any[];toast:(message:string)=>void;go:(key:any)=>void}){
 const activeCategories=expenseCategories.filter(category=>category.active);
 const [tab,setTab]=useState<"quick"|"detail"|"list">("quick"),[recentStatus,setRecentStatus]=useState("有效"),[recent,setRecent]=useState<any[]>([]),[busy,setBusy]=useState(false);
 const [quick,setQuick]=useState({date:today,category:activeCategories[0]?.name||"其他",amount:"",handler:"",note:""});
 const [detail,setDetail]=useState({date:today,handler:"",note:""}),[lines,setLines]=useState<Line[]>([blankLine()]);
 const [picker,setPicker]=useState<{row:number;query:string}|null>(null),[matches,setMatches]=useState<Product[]>([]),[inactiveMatches,setInactiveMatches]=useState<Product[]>([]);
 const [newProduct,setNewProduct]=useState<(Product&{row:number})|null>(null);

 useEffect(()=>{if(activeCategories.length&&!activeCategories.some(category=>category.name===quick.category))setQuick(current=>({...current,category:activeCategories[0].name}))},[expenseCategories]); // eslint-disable-line react-hooks/exhaustive-deps
 const refreshRecent=async()=>{try{const result=await recentExpensesV2(20,recentStatus);setRecent(result.items)}catch(error:any){toast(`读取近期支出失败：${error.message}`)}};
 useEffect(()=>{if(tab==="list")refreshRecent()},[tab,recentStatus]); // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{
  if(!picker){setMatches([]);setInactiveMatches([]);return}
  const timer=setTimeout(async()=>{try{const [active,inactive]=await Promise.all([listProductsV2(picker.query,true,20),picker.query.trim()?listProductsV2(picker.query,false,10):Promise.resolve({items:[]})]);setMatches(active.items);setInactiveMatches(inactive.items)}catch(error:any){toast(`搜索商品失败：${error.message}`)}},160);
  return()=>clearTimeout(timer);
 },[picker?.row,picker?.query]); // eslint-disable-line react-hooks/exhaustive-deps

 const saveQuick=async()=>{
  if(!quick.amount||Number(quick.amount)<=0||!quick.handler.trim())return toast("请填写正确的金额和经手人");
  setBusy(true);try{await createExpenseV2({date:quick.date,mode:"快速记账",category:quick.category,item:quick.note||quick.category,amountYuan:quick.amount,handler:quick.handler.trim(),note:quick.note,status:"有效"});setQuick(current=>({...current,amount:"",note:""}));toast("快速支出已保存");if(tab==="list")refreshRecent()}catch(error:any){toast(`保存失败：${error.message}`)}finally{setBusy(false)}
 };
 const chooseProduct=(row:number,product:Product)=>{setLines(current=>current.map((line,index)=>index===row?{...line,productId:product.id,item:product.name,category:product.category,unit:product.unit}:line));setPicker(null)};
 const editProductText=(row:number,value:string)=>{setLines(current=>current.map((line,index)=>index===row?{...line,productId:null,item:value,category:"",unit:"—"}:line));setPicker({row,query:value})};
 const openQuickProduct=(row:number,name:string)=>setNewProduct({id:0,row,name:name.trim(),category:"食材",brand:"",spec:"",unit:"kg",stocktake:true,reminder:false,active:true});
 const saveQuickProduct=async()=>{
  if(!newProduct?.name.trim())return toast("请填写商品名称");
  setBusy(true);try{const {row,...payload}=newProduct;const result=await upsertProductV2(payload);chooseProduct(row,result.item);setNewProduct(null);toast("商品已建档并加入本次采购")}catch(error:any){toast(`新增商品失败：${error.message}`)}finally{setBusy(false)}
 };
 const saveDetail=async()=>{
  if(!lines.length)return toast("请至少添加一行商品");
  const invalid=lines.findIndex(line=>!line.productId||Number(line.qty)<=0||Number(line.price)<=0);
  if(invalid>=0)return toast(`第 ${invalid+1} 行商品、数量或单价不完整`);
  if(!detail.handler.trim())return toast("请填写经手人");
  setBusy(true);try{const result=await createPurchaseV2({date:detail.date,handler:detail.handler.trim(),note:detail.note,lines:lines.map(line=>({productId:line.productId,qty:line.qty,priceYuan:line.price}))});setLines([blankLine()]);setDetail(current=>({...current,note:""}));toast(`采购单 ${result.purchaseNo} 已保存，共 ${result.lineCount} 项，合计 ${money(result.amount)}`)}catch(error:any){toast(`保存采购单失败：${error.message}`)}finally{setBusy(false)}
 };
 const editRecent=async(row:any)=>{const item=prompt("项目或备注",row.item);if(item===null)return;const amount=prompt("金额（元）",String(row.amount));if(amount===null||!Number.isFinite(Number(amount))||Number(amount)<=0)return toast("金额填写不正确");const handler=prompt("经手人",row.handler);if(handler===null||!handler.trim())return toast("经手人不能为空");setBusy(true);try{await updateExpenseV2(row.id,{item:item.trim()||row.item,amountYuan:amount,handler:handler.trim()});toast("支出记录已更新");await refreshRecent()}catch(error:any){toast(`修改失败：${error.message}`)}finally{setBusy(false)}};
 const copyRecent=async(row:any)=>{if(row.mode==="详细采购")return toast("详细采购请按整张采购单重新录入，避免复制单行造成采购单不完整");setBusy(true);try{await createExpenseV2({date:today,mode:row.mode,category:row.category,item:row.item,amountYuan:row.amount,handler:row.handler,note:row.note||"",status:"有效"});toast("已复制为一条新的今日记录");await refreshRecent()}catch(error:any){toast(`复制失败：${error.message}`)}finally{setBusy(false)}};
 const voidRecent=async(row:any)=>{if(!confirm("确认作废这条记录？作废后不会参与正常统计，但历史记录仍然保留。"))return;setBusy(true);try{await voidExpenseV2(row.id);toast("支出记录已作废");await refreshRecent()}catch(error:any){toast(`作废失败：${error.message}`)}finally{setBusy(false)}};
 const total=useMemo(()=>lines.reduce((sum,line)=>sum+Number(line.qty||0)*Number(line.price||0),0),[lines]);

 return <>
  <div className="head"><div><h1>采购支出</h1><p>快速记账、详细采购和近期业务操作；桌面版直接写入 SQLite 关系表</p></div></div>
  <div className="tabs"><button className={tab==="quick"?"on":""} onClick={()=>setTab("quick")}>快速记账</button><button className={tab==="detail"?"on":""} onClick={()=>setTab("detail")}>详细采购</button><button className={tab==="list"?"on":""} onClick={()=>setTab("list")}>最近支出</button></div>
  {tab==="quick"&&<div className="panel entry"><div><label>日期<input type="date" value={quick.date} onChange={event=>setQuick({...quick,date:event.target.value})}/></label><label>支出类别<select value={quick.category} onChange={event=>setQuick({...quick,category:event.target.value})}>{activeCategories.map(category=><option key={category.id}>{category.name}</option>)}</select></label><label>金额（元）<input type="number" min="0" step="0.01" value={quick.amount} onChange={event=>setQuick({...quick,amount:event.target.value})}/></label><label>经手人<input value={quick.handler} onChange={event=>setQuick({...quick,handler:event.target.value})}/></label><label className="wide">备注<textarea value={quick.note} onChange={event=>setQuick({...quick,note:event.target.value})}/></label><button className="btn" disabled={busy} onClick={saveQuick}>{busy?"正在保存…":"保存记账"}</button></div><aside><b>金额存储</b><p>界面按元录入，后端统一转为整数分存储，避免浮点金额累计误差。</p><strong>保存后立即进入关系数据库</strong></aside></div>}
  {tab==="detail"&&<div className="panel form detail-purchase-panel"><div className="filters"><label>采购日期<input type="date" value={detail.date} onChange={event=>setDetail({...detail,date:event.target.value})}/></label><label>经手人<input value={detail.handler} onChange={event=>setDetail({...detail,handler:event.target.value})}/></label><label>备注<input value={detail.note} onChange={event=>setDetail({...detail,note:event.target.value})}/></label></div><div className="purchase-tip"><b>整张采购单一次事务保存</b><span>输入商品名称、分类、品牌、规格或单位搜索商品；全部明细验证通过后一次性写入，任一行失败则整单不保存。</span></div><table className="dense purchase-table"><thead><tr><th>商品</th><th>分类</th><th>数量</th><th>单位</th><th>单价</th><th>小计</th><th/></tr></thead><tbody>{lines.map((line,index)=>{const current=picker?.row===index;return <tr key={index}><td><div className="purchase-picker"><div className={line.productId?"picker-input selected":"picker-input"}><span>⌕</span><input value={line.item} placeholder="搜索并选择商品" onFocus={()=>setPicker({row:index,query:line.item})} onChange={event=>editProductText(index,event.target.value)}/>{line.productId&&<i>✓</i>}</div>{current&&<div className="product-dropdown">{matches.length?<><small>可选商品</small>{matches.map(product=><button key={product.id} onMouseDown={event=>event.preventDefault()} onClick={()=>chooseProduct(index,product)}><span><b>{product.name}</b><em>{product.brand} {product.spec}</em></span><span>{product.category}<strong>{product.unit}</strong></span></button>)}</>:<p>没有找到启用中的商品</p>}{picker.query.trim()&&!matches.some(product=>product.name===picker.query.trim())&&<button className="quick-create-product" onMouseDown={event=>event.preventDefault()} onClick={()=>openQuickProduct(index,picker.query)}>＋ 新增“{picker.query.trim()}”到商品档案</button>}{inactiveMatches.length>0&&<div className="inactive-match"><small>已停用，不可选择</small>{inactiveMatches.map(product=><span key={product.id}>{product.name} · {product.unit}</span>)}</div>}</div>}</div></td><td>{line.category||<span className="muted">选择后带出</span>}</td><td><input type="number" min="0" step="0.001" value={line.qty} onChange={event=>setLines(current=>current.map((item,i)=>i===index?{...item,qty:Number(event.target.value)}:item))}/></td><td><span className="auto-value">{line.unit}</span></td><td><input type="number" min="0" step="0.01" value={line.price} onChange={event=>setLines(current=>current.map((item,i)=>i===index?{...item,price:Number(event.target.value)}:item))}/></td><td>{money(line.qty*line.price)}</td><td><button className="danger" onClick={()=>setLines(current=>current.filter((_,i)=>i!==index))}>移除</button></td></tr>})}</tbody></table><div className="tablefoot"><button className="btn soft" onClick={()=>setLines(current=>[...current,blankLine()])}>＋ 新增一行</button><strong>采购合计：{money(total)}</strong><button className="btn" disabled={busy} onClick={saveDetail}>{busy?"正在保存…":"保存采购单"}</button></div></div>}
  {tab==="list"&&<div className="panel recent-panel"><div className="recent-head"><div><b>最近20条支出</b><span>由数据库按日期和 ID 倒序查询，不加载全部历史支出</span></div><div className="recent-head-actions"><label>状态<select value={recentStatus} onChange={event=>setRecentStatus(event.target.value)}><option>有效</option><option>已作废</option><option>全部</option></select></label><button className="link" onClick={()=>go("reports")}>查看全部支出记录 →</button></div></div><table><thead><tr><th>日期</th><th>方式</th><th>类别</th><th>项目</th><th>金额</th><th>经手人</th><th>状态</th><th>操作</th></tr></thead><tbody>{recent.map(row=><tr key={row.id} className={row.status!=="有效"?"void":""}><td>{row.date}</td><td><span className="tag">{row.mode}</span></td><td>{row.category}</td><td>{row.item}</td><td><b>{money(row.amount)}</b></td><td>{row.handler}</td><td>{row.status}</td><td className="row-actions"><button className="link" onClick={()=>alert(`日期：${row.date}\n方式：${row.mode}\n类别：${row.category}\n项目：${row.item}\n金额：${money(row.amount)}\n经手人：${row.handler}\n状态：${row.status}${row.purchaseNo?`\n采购单号：${row.purchaseNo}`:""}`)}>查看</button><button className="link" disabled={busy||row.status!=="有效"} onClick={()=>editRecent(row)}>修改</button><button className="link" disabled={busy||row.mode==="详细采购"} title={row.mode==="详细采购"?"详细采购请按整单重新录入":""} onClick={()=>copyRecent(row)}>复制</button><button className="danger" disabled={busy||row.status!=="有效"} onClick={()=>voidRecent(row)}>作废</button></td></tr>)}</tbody></table>{!recent.length&&<div className="empty-state">当前条件下没有近期支出。</div>}<div className="recent-foot"><span>最多显示最近20条；完整历史记录请前往“查询统计—支出查询”。</span><button className="link" onClick={()=>go("reports")}>进入支出查询 →</button></div></div>}
  {newProduct&&<div className="shade" onMouseDown={event=>event.currentTarget===event.target&&setNewProduct(null)}><div className="modal"><div><h2>快速新增商品</h2><button onClick={()=>setNewProduct(null)}>×</button></div><div className="snapshot-notice"><b>新增后立即可用</b><span>商品保存到关系表，并自动加入当前采购行。</span></div><label>商品名称<input autoFocus value={newProduct.name} onChange={event=>setNewProduct({...newProduct,name:event.target.value})}/></label><label>商品类别<select value={newProduct.category} onChange={event=>setNewProduct({...newProduct,category:event.target.value})}>{productCategories.map(category=><option key={category}>{category}</option>)}</select></label><div className="product-form-row"><label>品牌<input value={newProduct.brand} onChange={event=>setNewProduct({...newProduct,brand:event.target.value})}/></label><label>规格<input value={newProduct.spec} onChange={event=>setNewProduct({...newProduct,spec:event.target.value})}/></label><label>计量单位<select value={newProduct.unit} onChange={event=>setNewProduct({...newProduct,unit:event.target.value})}>{units.map(unit=><option key={unit}>{unit}</option>)}</select></label></div><div className="product-switches"><label><input type="checkbox" checked={newProduct.stocktake} onChange={event=>setNewProduct({...newProduct,stocktake:event.target.checked})}/>参与盘点</label><label><input type="checkbox" checked={newProduct.reminder} onChange={event=>setNewProduct({...newProduct,reminder:event.target.checked})}/>启用补货提醒</label></div><footer><button className="btn soft" onClick={()=>setNewProduct(null)}>取消</button><button className="btn" disabled={busy} onClick={saveQuickProduct}>保存</button></footer></div></div>}
 </>;
}
