"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import React,{useEffect,useMemo,useState} from "react";
import {generatePayrollV2,getPayrollV2,listEmployeesV2,savePayrollV2,upsertEmployeeV2} from "./management-api-v2";

const today=new Date().toISOString().slice(0,10);
const money=(n:number)=>`¥ ${Number(n||0).toLocaleString("zh-CN",{minimumFractionDigits:2,maximumFractionDigits:2})}`;

export default function PayrollV2({toast}:{toast:(message:string)=>void}){
 const [tab,setTab]=useState<"wage"|"employees">("wage"),[month,setMonth]=useState(today.slice(0,7)),[payroll,setPayroll]=useState<any>({month:today.slice(0,7),confirmed:false,rows:[]}),[employees,setEmployees]=useState<any[]>([]),[employeeDialog,setEmployeeDialog]=useState<any>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false);
 const loadPayroll=async(target=month)=>{setLoading(true);try{const result=await getPayrollV2(target);setPayroll({month:result.month,confirmed:result.confirmed,rows:result.rows});setEmployees(result.employees||[])}catch(error:any){toast(`读取工资表失败：${error.message}`)}finally{setLoading(false)}};
 const loadEmployees=async()=>{try{const result=await listEmployeesV2();setEmployees(result.items)}catch(error:any){toast(`读取员工失败：${error.message}`)}};
 useEffect(()=>{loadPayroll(month)},[month]); // eslint-disable-line react-hooks/exhaustive-deps
 const updateWage=(employeeId:number,patch:any)=>setPayroll((current:any)=>({...current,rows:current.rows.map((row:any)=>row.employeeId===employeeId?{...row,...patch}:row)}));
 const total=useMemo(()=>payroll.rows.reduce((sum:number,row:any)=>sum+Number(row.amount||0),0),[payroll.rows]);
 const generate=async()=>{setBusy(true);try{const result=await generatePayrollV2(month);setPayroll(result.item);toast(`已按 ${result.item.rows.length} 名在职员工的标准月薪生成工资快照`)}catch(error:any){toast(`生成工资表失败：${error.message}`)}finally{setBusy(false)}};
 const saveAdjustments=async()=>{if(payroll.confirmed)return toast("工资表已确认，请先撤销确认");if(!payroll.rows.length)return toast("工资表为空，请先生成");setBusy(true);try{const result=await savePayrollV2({...payroll,confirmed:false});setPayroll(result.item);toast("工资调整已保存")}catch(error:any){toast(`保存工资失败：${error.message}`)}finally{setBusy(false)}};
 const toggleConfirm=async()=>{if(!payroll.rows.length)return toast("工资表为空，请先生成");setBusy(true);try{const result=await savePayrollV2({...payroll,confirmed:!payroll.confirmed});setPayroll(result.item);toast(result.item.confirmed?"工资已确认并锁定；员工档案以后调薪不会改写本月快照":"已撤销工资确认，可继续调整")}catch(error:any){toast(`更新确认状态失败：${error.message}`)}finally{setBusy(false)}};
 const saveEmployee=async()=>{if(!employeeDialog?.name.trim()||!employeeDialog.role.trim())return toast("请填写员工姓名和岗位");if(Number(employeeDialog.salary)<0)return toast("标准月薪不能小于 0");setBusy(true);try{const exists=Boolean(employeeDialog.id);await upsertEmployeeV2(employeeDialog);setEmployeeDialog(null);await loadEmployees();toast(exists?"员工档案已更新；现有工资快照未改变":"员工已新增，可重新生成工资表")}catch(error:any){toast(`保存员工失败：${error.message}`)}finally{setBusy(false)}};
 const toggleEmployee=async(employee:any)=>{setBusy(true);try{await upsertEmployeeV2({...employee,active:!employee.active});await loadEmployees();toast(employee.active?"员工已设为离职；历史工资不受影响":"员工已恢复在职")}catch(error:any){toast(`更新员工状态失败：${error.message}`)}finally{setBusy(false)}};
 const activeEmployees=employees.filter(employee=>employee.active);
 return <>
  <div className="head"><div><h1>员工与工资</h1><p>标准月薪在员工档案中定义，每月工资保存独立快照</p></div><div>{tab==="employees"?<button className="btn" onClick={()=>setEmployeeDialog({id:0,name:"",role:"服务员",salary:0,startDate:today,active:true})}>＋ 新增员工</button>:<button className="btn soft" disabled={busy||payroll.confirmed} onClick={generate}>重新生成工资表</button>}</div></div>
  <div className="tabs"><button className={tab==="wage"?"on":""} onClick={()=>setTab("wage")}>本月工资表</button><button className={tab==="employees"?"on":""} onClick={()=>setTab("employees")}>员工档案</button></div>
  {tab==="wage"&&<><div className="filters payroll-head"><label>工资月份<input type="month" value={month} disabled={payroll.confirmed} onChange={event=>setMonth(event.target.value)}/></label><span className={payroll.confirmed?"ok":"warn"}>{payroll.confirmed?"已确认并锁定":"待确认"}</span><span className="info">生成时保存姓名、岗位和标准月薪快照</span></div><div className="panel payroll-panel"><div className="snapshot-notice"><b>工资来源</b><span>标准月薪来自员工档案；本月工资可按请假、奖金等调整。员工档案后续调薪不会回写已经生成的月份。</span></div><table><thead><tr><th>姓名</th><th>岗位</th><th>标准月薪快照</th><th>本月工资</th><th>调整</th><th>备注</th></tr></thead><tbody>{payroll.rows.map((row:any)=><tr key={row.employeeId}><td><b>{row.name}</b></td><td>{row.role}</td><td>{money(row.standard)}</td><td><input type="number" min="0" step="0.01" value={row.amount} disabled={payroll.confirmed} onChange={event=>updateWage(row.employeeId,{amount:Math.max(0,Number(event.target.value)||0)})}/></td><td><b className={row.amount-row.standard<0?"down":"up"}>{row.amount-row.standard>0?"+":""}{money(row.amount-row.standard)}</b></td><td><input value={row.note} disabled={payroll.confirmed} placeholder="如奖金、请假" onChange={event=>updateWage(row.employeeId,{note:event.target.value})}/></td></tr>)}</tbody><tfoot><tr><td colSpan={3}>合计</td><td>{money(total)}</td><td colSpan={2}/></tr></tfoot></table>{loading&&<div className="empty-state">正在读取工资表…</div>}{!loading&&!payroll.rows.length&&<div className="empty-state">暂无工资记录，请点击“重新生成工资表”。</div>}<div className="tablefoot"><span>调整内容需明确保存；确认后锁定本月工资。</span><div><button className="btn soft" disabled={busy||payroll.confirmed||!payroll.rows.length} onClick={saveAdjustments}>保存调整</button><button className={payroll.confirmed?"btn soft":"btn"} disabled={busy||!payroll.rows.length} onClick={toggleConfirm}>{payroll.confirmed?"撤销确认":"确认工资"}</button></div></div></div></>}
  {tab==="employees"&&<div className="panel employee-panel"><div className="employee-summary"><div><b>{activeEmployees.length}</b><span>在职员工</span></div><div><b>{money(activeEmployees.reduce((sum:number,employee:any)=>sum+Number(employee.salary||0),0))}</b><span>在职标准月薪合计</span></div><p>员工调薪从下次重新生成工资表开始生效，不影响历史工资。</p></div><table><thead><tr><th>姓名</th><th>岗位</th><th>标准月薪</th><th>入职日期</th><th>状态</th><th>操作</th></tr></thead><tbody>{employees.map(employee=><tr key={employee.id} className={employee.active?"":"inactive-product"}><td><b>{employee.name}</b></td><td>{employee.role}</td><td>{money(employee.salary)}</td><td>{employee.startDate}</td><td><span className={employee.active?"yes":"tag"}>{employee.active?"在职":"已离职"}</span></td><td className="row-actions"><button className="link" onClick={()=>setEmployeeDialog({...employee})}>编辑</button><button className="link" disabled={busy} onClick={()=>toggleEmployee(employee)}>{employee.active?"设为离职":"恢复在职"}</button></td></tr>)}</tbody></table></div>}
  {employeeDialog&&<div className="shade" onMouseDown={event=>event.currentTarget===event.target&&setEmployeeDialog(null)}><div className="modal"><div><h2>{employeeDialog.id?"编辑员工档案":"新增员工"}</h2><button onClick={()=>setEmployeeDialog(null)}>×</button></div><div className="snapshot-notice"><b>工资定义位置</b><span>标准月薪在这里维护。变更只影响以后重新生成的工资表，已经生成或确认的月份保留原快照。</span></div><div className="employee-form-row"><label>员工姓名<input autoFocus value={employeeDialog.name} onChange={event=>setEmployeeDialog({...employeeDialog,name:event.target.value})}/></label><label>岗位<input value={employeeDialog.role} onChange={event=>setEmployeeDialog({...employeeDialog,role:event.target.value})}/></label></div><div className="employee-form-row"><label>标准月薪（元）<input type="number" min="0" step="0.01" value={employeeDialog.salary} onChange={event=>setEmployeeDialog({...employeeDialog,salary:Math.max(0,Number(event.target.value)||0)})}/></label><label>入职日期<input type="date" value={employeeDialog.startDate} onChange={event=>setEmployeeDialog({...employeeDialog,startDate:event.target.value})}/></label></div><div className="product-switches"><label><input type="checkbox" checked={employeeDialog.active} onChange={event=>setEmployeeDialog({...employeeDialog,active:event.target.checked})}/>当前在职</label></div><footer><button className="btn soft" onClick={()=>setEmployeeDialog(null)}>取消</button><button className="btn" disabled={busy} onClick={saveEmployee}>{busy?"正在保存…":"保存"}</button></footer></div></div>}
 </>;
}
